# This file was generated by GoReleaser. DO NOT EDIT.
cask "pair" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "625fc3587f7a10e52a42625a4d82dc99f65a38061a708da72550392f09ffa15c"
      url "https://github.com/fabioaraujo121/pair-releases/releases/download/v#{version}/pair_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7fb895d89640c054cab100d01bfdf95de6c46e17cde48c033652f959887abb4d"
      url "https://github.com/fabioaraujo121/pair-releases/releases/download/v#{version}/pair_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "pair"
  desc "Voice-driven pairing with a coding agent (Claude Code, Codex) in the terminal"
  homepage "https://github.com/fabioaraujo121/pair-releases"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "neovim",
      "sox",
      "tmux",
      "whisper.cpp",
    ]

  binary "pair"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pair"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Recommended: brew install git-delta (pretty diffs) and
    brew install --cask hammerspoon (global push-to-talk hotkeys).
    whisper.cpp ships no model: run `pair doctor --fix` to download one,
    then `pair doctor --mic` once to grant microphone access.
    In a repository: `pair init`, then `pair`.
  EOS
end
