# This file was generated by GoReleaser. DO NOT EDIT.
cask "pair" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "4d7c821a11ac0cf307db58c0a3de8846cb26a07a5b9e32066f4ec33effeb1d1b"
      url "https://github.com/fabioaraujo121/pair-releases/releases/download/v#{version}/pair_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e6877bb8b5a0d2c83f7b7ee0bc7236381a9e9ce373219c36f5f6572255c9de8"
      url "https://github.com/fabioaraujo121/pair-releases/releases/download/v#{version}/pair_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "pair"
  desc "Voice-driven pairing with a coding agent (Claude Code, Codex) in the terminal"
  homepage "https://github.com/fabioaraujo121/pair-releases"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "neovim",
      "sox",
      "tmux",
      "whisper.cpp",
    ]

  binary "pair"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pair"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Recommended: brew install git-delta (pretty diffs) and
    brew install --cask hammerspoon (global push-to-talk hotkeys).
    whisper.cpp ships no model: run `pair doctor --fix` to download one,
    then `pair doctor --mic` once to grant microphone access.
    In a repository: `pair init`, then `pair`.
  EOS
end
